--liquibase formatted.sql
--changeset michael.cawayan:INT_OS.V_DICT_DYNAMIC_OFFER_PRIO contextFilter:PH endDelimiter:/ runOnChange:true

CREATE OR REPLACE EDITIONABLE VIEW "INT_OS"."V_DICT_DYNAMIC_OFFER_PRIO" (
  RANUNI_SEGMENT,
  CRM_PILOTCODE,
  SCORE,
  offerTypePriority,
  VALIDITYTIMESTAMP
) AS
SELECT 
  RANUNI_SEGMENT,
  CRM_PILOTCODE,
  SCORE,
  PRIORITY AS offerTypePriority,
  SYSTIMESTAMP + INTERVAL '30' DAY AS VALIDITYTIMESTAMP
FROM INT_OS.DICT_DYNAMIC_OFFER_PRIO
/
GRANT SELECT ON "INT_OS"."V_DICT_DYNAMIC_OFFER_PRIO" TO "SAS_INT_OS_RO"
/
GRANT SELECT ON "INT_OS"."V_DICT_DYNAMIC_OFFER_PRIO" TO "MA_TEMP"
/
GRANT SELECT ON "INT_OS"."V_DICT_DYNAMIC_OFFER_PRIO" TO "HCI_RO_INT_OS"
/